name: Build, Lint and Unit Tests for Momoka NODE

on:
  pull_request:
    types: [labeled, opened, synchronize, unlabeled]
    # Run only for the momoka-node directory
    paths:
      - 'momoka-node/**'

jobs:
  build-lint-test:
    name: Build-Lint-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
  
      - name: Install dependencies
        run: cd momoka-node && pnpm install
      
      - name: Lint the code
        run: cd momoka-node && pnpm run lint

      - name: Build the packages
        run: cd momoka-node && pnpm run build

      - name: Run the unit tests
        run: cd momoka-node && pnpm run test:ci

